Add option to disable NAT iptables rules
WeeJeWel/wg-easy pull request #43
Opened 2021-07-14 07:46 UTC by principis

I would like to use wg-easy with `--network=host` to easily manage the interface and add custom iptables rules. This requires some changes, one of the most important is this one.

This PR disables the iptables rules. I've called it `NAT rules` because in my testing the other 3 rules for INPUT and FORWARD aren't useful because the default policy is already ACCEPT. If you want, I can remove the excess lines, change the naming of the option or leave it as is.

Let me know if you want me to combine everything in a single pull request. These are the patches I would like to submit:
- [ ] Add a hostname option to specify the listening address for the UI instead of `0.0.0.0`
- [ ] Add a keep-alive option
- [ ] Add a WG_LISTEN_PORT option to change the port the interface listens on.
- [ ] Add a wg-interface option to be able to change the wireguard interface (e.g `wg0` -> `wg1`)
- [x] Be able to disable DNS (just fixed :slightly_smiling_face: )

2021-07-14 08:16 UTC, WeeJeWel commented
I'm not sure I understand. Is your goal to run WireGuard outside of Docker, and just run the Web UI inside it?

2021-07-14 09:00 UTC, principis commented
> I'm not sure I understand. Is your goal to run WireGuard outside of Docker, and just run the Web UI inside it?

Yes. This allows more control over the interface.

2021-07-14 09:01 UTC, WeeJeWel commented
Sorry but I'm not interested in that. Just run the node.js project on your host :)

2021-07-14 09:15 UTC, principis commented
Even if I would run it without docker, I still need to be able to disable the iptables rules. The other features are like this, just an extra option and a few lines of code, but I can live without them if you don't want to accept them.

2021-08-19 16:11 UTC, maarken commented
I would also like this merged as the NAT causes issues with VOIP through the VPN and I actually need is a static route.

2021-08-28 18:07 UTC, chancez commented
👍 I currently use macvlan networks for most of my containers and the iptables rule is preventing that from working.

2021-08-28 18:08 UTC, chancez approved these changes

2021-09-10 03:14 UTC, gaby commented
Any plans to merge this? Having this flag is a valid use-case. Macvlan, ipvlan, vlan trunk networks are affected by these NAT rules in the container.

2021-10-11 20:18 UTC, WeeJeWel requested changes

2021-10-11 20:18 UTC, WeeJeWel commented on src/config.js
> +module.exports.WG_NAT = process.env.WG_NAT || true;
I think you need to parse this, e.g.

```js
typeof process.env.WG_NAT === 'string'
  ? process.env.WG_NAT === '1'
  : true
```

2021-12-28 10:16 UTC, principis commented
Closing this since the license is still not FOSS and very vague. I am also no longer interested in this project. 

It would probably be best for maintainers and contributors to adopt a [open source license](https://opensource.org/licenses).

2021-12-28 10:16 UTC, closed without merging